sudo: required
services:
  - docker

before_install:
  - docker build -t pradeepyrl/react-test -f ./client/Dockerfile.dev ./client/

script:
  - docker run -e CI=true pradeepyrl/react-test npm test

after_success:
  - docker build -t pradeepyrl/multi-client ./client
  - docker build -t pradeepyrl/multi-nginx ./nginx
  - docker build -t pradeepyrl/multi-server ./server
  - docker build -t pradeepyrl/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push pradeepyrl/multi-client
  - docker push pradeepyrl/multi-nginx
  - docker push pradeepyrl/multi-server
  - docker push pradeepyrl/multi-worker
